version: "3.7"
services:
    app:
        image: "node:14"
        container_name: "vt-admin-app"
        working_dir: /app
        command: /bin/bash -c "npm install && npm run serve"
        ports:
            - "50000:50000"
        volumes:
            - ./:/app
        restart: unless-stopped
        environment:
            - HOST=0.0.0.0
